# Python Basics

In [1]:
print("Hello, AYESHA IMRAN!")

Hello, AYESHA IMRAN!


In [2]:
a = 10
b = 5
print("Sum:", a + b)

Sum: 15


### Loops (All Types)

Loops are used to repeat a block of code multiple times.
Python supports different types of loops such as for loop, while loop,
and nested loops.

#### 1 : For loop

In [3]:
for i in range(1, 6):
    print(i)


1
2
3
4
5


#### 2 : while loop

In [4]:
count = 1
while count <= 5:
    print(count)
    count += 1


1
2
3
4
5


#### 3 : nested loop

In [7]:
for i in range(1, 4):
    for j in range(1, 3):
        print(i, j)


1 1
1 2
2 1
2 2
3 1
3 2


#### 4 : break & continue

In [6]:
for i in range(1, 6):
    if i == 3:
        continue
    if i == 5:
        break
    print(i)


1
2
4


### Functions (All Types)

A function is a block of reusable code that performs a specific task.
Functions make code easier to understand, reuse, and manage.

#### 1 : Function without arguments

In [8]:
def greet():
    print("Hello Ayesha!")
greet()


Hello Ayesha!


#### 2 : Function with arguments

In [9]:
def add(a, b):
    return a + b
print(add(3, 4))


7


#### 3 : Default arguments

In [10]:
def welcome(name="Student"):
    print("Welcome", name)
welcome()
welcome("Ayesha")

Welcome Student
Welcome Ayesha


#### 4 : Keyword arguments

In [11]:
def student(name, age):
    print(name, age)

student(age=20, name="Ayesha")

Ayesha 20


#### 5 : Lambda function

In [12]:
square = lambda x: x * x
print(square(5))

25


### Lists 

A list is a collection data type in Python that can store multiple values
in a single variable. Lists are ordered, changeable, and allow duplicate values.

#### 1. append()  
Adds a new element at the end of the list.

In [16]:
my_list = [1, 2, 3]
my_list.append(4)
print(my_list)

[1, 2, 3, 4]


#### 2. insert()  
Inserts an element at a specified index position.


In [17]:
my_list = [1, 2, 3]
my_list.insert(1, 10)
print(my_list)


[1, 10, 2, 3]


#### 3. extend()  
Adds elements of another list to the current list.


In [18]:
my_list = [1, 2, 3]
my_list.extend([4, 5])
print(my_list)


[1, 2, 3, 4, 5]


#### 4. remove()  
Removes the first occurrence of a specific value from the list.

In [19]:
my_list = [1, 2, 3, 2]
my_list.remove(2)
print(my_list)


[1, 3, 2]


#### 5. pop()  
Removes and returns the last element or the element at a given index.


In [20]:
my_list = [1, 2, 3]
my_list.pop()
print(my_list)


[1, 2]


In [21]:
my_list = [1, 2, 3]
my_list.pop(0)
print(my_list)


[2, 3]


#### 6. clear()  
Removes all elements from the list and makes it empty.


In [22]:
my_list = [1, 2, 3]
my_list.clear()
print(my_list)


[]


#### 7. index()  
Returns the index number of the first occurrence of a value.


In [23]:
my_list = [10, 20, 30]
print(my_list.index(20))


1


#### 8. count()  
Counts how many times a specific value appears in the list.

In [24]:
my_list = [1, 2, 2, 3, 2]
print(my_list.count(2))


3


#### 9. sort()  
Sorts the list in ascending order


In [25]:
my_list = [3, 1, 4, 2]
my_list.sort()
print(my_list)


[1, 2, 3, 4]


#### 10. reverse()  
Reverses the order of elements in the list.


In [26]:
my_list = [1, 2, 3, 4]
my_list.reverse()
print(my_list)


[4, 3, 2, 1]


#### 11. copy()  
Creates a shallow copy of the list.


In [27]:
my_list = [1, 2, 3]
new_list = my_list.copy()
print(new_list)


[1, 2, 3]


#### 12. len()  
Returns the total number of elements in the list.


In [28]:
my_list = [1, 2, 3, 4]
print(len(my_list))


4


#### 13. max()  
Returns the largest value from the list.


In [29]:
my_list = [5, 2, 9, 1]
print(max(my_list))


9


#### 14. min()  
Returns the smallest value from the list.


In [30]:
my_list = [5, 2, 9, 1]
print(min(my_list))


1


### Dictionaries

A dictionary is a collection of key-value pairs.
It is unordered, changeable, and does not allow duplicate keys.
Dictionaries are used to store data values like student records.

#### Dictionary Creation

In [31]:
student = {"name": "Ayesha", "age": 20, "grade": "A"}

#### List to Dictionary

A list can be converted into a dictionary using the zip() function,
where one list is used as keys and another list as values.

In [32]:
keys = ["a", "b", "c"]
values = [1, 2, 3]
dict_from_list = dict(zip(keys, values))
print(dict_from_list)

{'a': 1, 'b': 2, 'c': 3}


#### Dictionary to List

Keys and values of a dictionary can be converted into lists using
keys() and values() methods.

In [33]:
dict_keys = list(student.keys())
dict_values = list(student.values())
print(dict_keys)
print(dict_values)

['name', 'age', 'grade']
['Ayesha', 20, 'A']


### Tuples

A tuple is an ordered and unchangeable collection of elements.
Tuples are used when data should not be modified.

In [34]:
my_tuple = (10, 20, 30)
print(my_tuple)

(10, 20, 30)


# NumPy

NumPy is a powerful Python library used for numerical computing.
It provides support for large multi-dimensional arrays and
high-level mathematical functions.

In [35]:
import numpy as np

### Arrays

NumPy arrays are used to store multiple values of the same data type.
They are faster and more efficient than Python lists.

#### 1D Array

In [36]:
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


#### 2D Array

In [37]:
matrix = np.array([[1, 2], [3, 4]])
print(matrix)

[[1 2]
 [3 4]]


### Vectorized Operations

Vectorized operations allow mathematical operations to be performed
on entire arrays without using loops. This makes the code faster
and easier to write.

In [38]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a * b)

[5 7 9]
[ 4 10 18]


# Advanced NumPy

### Matrix Multiplication

Matrix multiplication is a mathematical operation where rows of the
first matrix are multiplied with columns of the second matrix.
It is widely used in neural networks and deep learning models.

In [39]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

result = np.dot(A, B)
print(result)

[[19 22]
 [43 50]]


### Broadcasting

Broadcasting is a NumPy feature that allows arrays of different shapes
to perform arithmetic operations by automatically expanding the smaller array.

In [40]:
array = np.array([1, 2, 3])
number = 5

print(array + number)

[6 7 8]
